import re
from datetime import datetime
from source.schemas.secsgem import EquipmentSpec

class SmartAutomationService:
    def __init__(self):
        pass

    def _clean_identifier(self, name: str, fallback: str) -> str:
        if not name or name in ("-", "unknown"):
            return fallback
        # Replace non-alphanumeric chars with underscore
        clean = re.sub(r'[^a-zA-Z0-9_]', '_', name)
        # Ensure it doesn't start with a number
        if clean and clean[0].isdigit():
            clean = f"_{clean}"
        return clean

    def _xml_comment(self, summary: str, indent: int = 8) -> str:
        if not summary or summary == "-":
            return ""
        pad = " " * indent
        # Escape XML chars
        summary = summary.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        return f"{pad}/// <summary>\n{pad}/// {summary}\n{pad}/// </summary>\n"

    def generate_csharp_constants(self, spec: EquipmentSpec, namespace: str = "HiCore.EAPIntegration.EquipmentConstants") -> str:
        lines = []
        lines.append(f"// Auto-generated by EAP Bot on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"// Tool: {spec.ToolID or 'Unknown'} ({spec.ToolType or 'Unknown'})")
        lines.append("using System;")
        lines.append("")
        lines.append(f"namespace {namespace}")
        lines.append("{")

        # --- CEID Enum ---
        lines.append("    public enum CEID : uint")
        lines.append("    {")
        seen_ceids = set()
        for ev in sorted(spec.Events, key=lambda x: x.CEID):
            if ev.CEID in seen_ceids: continue
            seen_ceids.add(ev.CEID)
            name = self._clean_identifier(ev.EventName, f"Event_{ev.CEID}")
            desc = f"{ev.Description}"
            if ev.LinkedVIDs:
                desc += f" [Linked VIDs: {','.join(map(str, ev.LinkedVIDs))}]"
            lines.append(self._xml_comment(desc, 8).rstrip("\n"))
            lines.append(f"        {name} = {ev.CEID},")
        lines.append("    }")
        lines.append("")

        # --- SVID Enum ---
        lines.append("    public enum SVID : uint")
        lines.append("    {")
        seen_svids = set()
        for sv in sorted(spec.StatusVariables, key=lambda x: x.SVID):
            if sv.SVID in seen_svids: continue
            seen_svids.add(sv.SVID)
            name = self._clean_identifier(sv.Name, f"SVID_{sv.SVID}")
            desc = f"{sv.Description} (Type: {sv.DataType}, Access: {sv.AccessType})"
            lines.append(self._xml_comment(desc, 8).rstrip("\n"))
            lines.append(f"        {name} = {sv.SVID},")
        lines.append("    }")
        lines.append("")

        # --- DVID Enum ---
        if spec.DataVariables:
            lines.append("    public enum DVID : uint")
            lines.append("    {")
            seen_dvids = set()
            for dv in sorted(spec.DataVariables, key=lambda x: getattr(x, 'DvID', getattr(x, 'DVID', 0))):
                dvid = getattr(dv, 'DvID', getattr(dv, 'DVID', 0))
                if dvid in seen_dvids: continue
                seen_dvids.add(dvid)
                name = self._clean_identifier(dv.Name, f"DVID_{dvid}")
                desc = f"(Type: {dv.ValueType}, Unit: {dv.Unit})"
                lines.append(self._xml_comment(desc, 8).rstrip("\n"))
                lines.append(f"        {name} = {dvid},")
            lines.append("    }")
            lines.append("")

        # --- ALID Enum ---
        lines.append("    public enum ALID : uint")
        lines.append("    {")
        seen_alids = set()
        for al in sorted(spec.Alarms, key=lambda x: getattr(x, 'AlarmID', getattr(x, 'ALID', 0))):
            alid = getattr(al, 'AlarmID', getattr(al, 'ALID', 0))
            if alid in seen_alids: continue
            seen_alids.add(alid)
            name = self._clean_identifier(getattr(al, 'AlarmName', getattr(al, 'Name', f"Alarm_{alid}")), f"Alarm_{alid}")
            desc = f"Severity: {getattr(al, 'Severity', 'unknown')}"
            lines.append(self._xml_comment(desc, 8).rstrip("\n"))
            lines.append(f"        {name} = {alid},")
        lines.append("    }")
        lines.append("")

        # --- Remote Commands ---
        lines.append("    public static class RCMD")
        lines.append("    {")
        seen_rcmds = set()
        for rc in spec.RemoteCommands:
            if rc.RCMD in seen_rcmds: continue
            seen_rcmds.add(rc.RCMD)
            name = self._clean_identifier(rc.RCMD, "UnknownCommand")
            lines.append(self._xml_comment(rc.Description, 8).rstrip("\n"))
            lines.append(f'        public const string {name} = "{rc.RCMD}";')
        lines.append("    }")
        lines.append("}")
        lines.append("")

        # Remove empty lines with just whitespace
        return "\n".join(line if line.strip() else "" for line in lines)
